### PR TITLE
typo - missing self for an intent to call method

### PR DESCRIPTION
**Pull request by kares**
... or so it seems

### CODE REVIEW

**Review by benlangfeld — COMMENTED** [review]
Does this cause some bug that could be demonstrated in a test?

**Comment by kares** [comment]
> Does this cause some bug that could be demonstrated in a test?

nope its a typo - it should be the same if the line is removed except for not having @ivar initialized to nil

**Comment by benlangfeld** [comment]
So this line of code is useless either way? Why not remove it?

**Comment by kares** [comment]
lost track of this one ...
> So this line of code is useless either way? Why not remove it?

having the ivar layout up front might be preferable but I do not care, do you prefer do remove than?
(some ivar access optimizations might like it) anyway, seems that it never did what was intended: https://github.com/adhearsion/punchblock/commit/4334b9921e72811da267f7e1bb4b064549c4f322

**Comment by sfgeorge** [comment]
> So this line of code is useless either way? Why not remove it?

I think it's a good change, actually - as `ruby -w test.rb` (contents below) reveal that the old version is emitting 2 warnings:

```ruby
class Asterisk
  def self.event_filter=(filter)
    @event_filter = filter
  end

  def self.event_passes_filter?(event)
    @event_filter ? !!@event_filter[event] : true
  end

  event_filter = nil
end

Asterisk.event_passes_filter? :foo
```

> test.rb:10: warning: assigned but unused variable - event_filter
> test.rb:7: warning: instance variable @event_filter not initialized

With the update, both warnings are resolved.  A unit test for this would be great - I can help with that.

@benlangfeld Any objections to us using `Kernal.enable_warnings { test .... }` [from ActiveSupport](https://edgeguides.rubyonrails.org/active_support_core_extensions.html#silencing-warnings-and-exceptions) in order to temporarily bump warning level?  Or are we trying to avoid further entrenching in ActiveSupport as a dependency?

**Comment by bklang** [comment]
@sfgeorge To respond to your question, if ActiveSupport is a dependency of the framework, then as far as I'm concerned, using its features is fair game. I don't believe anyone has talked about trying to break a dependency on ActiveSupport.

Also, @benlangfeld has his energies focused on things other than Adhearsion at the moment. Please feel free to discuss with the other current maintainers (namely @lpradovera) and feel free to merge once you have consensus.

**Comment by sfgeorge** [comment]
@bklang Sorry, I was getting ahead of myself thinking that [adhearsion-asterisk's dropping of ActiveSupport as a dependency](https://github.com/adhearsion/adhearsion-asterisk/blob/develop/CHANGELOG.md#v151) was part of a larger trend.  Helpful that we can use some of those handy tricks here.

I'll pick Mr. @lpradovera's brain on this & other topics (🏎  🍷  🍝  👢 ).  Thanks very much! =D

**Review by bklang — APPROVED** [review]
The difference of opinion here feels very minor, and since this is known to work, I'm approving it so we can close this out.

**Pull request merged**
