### PR TITLE
12factor compliance (remove daemonisation and log persistence)

### PR DESCRIPTION
**Pull request by benlangfeld**
Encourage http://12factor.net/processes

### CODE REVIEW

**Comment by bklang** [comment]
:-1: I disagree. I like 12 factor, and we should support it, but daemonization is too important to drop.  It's a very common deployment target, and not everyone is on board with 12-factor, especially in the telephony world.

**Comment by benlangfeld** [comment]
Can you name a single deployment of Adhearsion that requires daemonisation that we care about?

**Comment by bklang** [comment]
I can, but I can't here.  Will send you privately.

**Comment by benlangfeld** [comment]
So as it turns out, neither of the two deployments which @bklang named privately actually use our daemonisation, instead relying on `start-stop-daemon` and similar, which are in effect implementations of the 12factor recommendation.

The remaining concern is that, by removing what is a traditionally understood feature from Adhearsion, the burden of documenting our recommendation for an improved way is on us. As such, we need to include on adhearsion.com a full tutorial on deployment to traditional environments. It is my belief that this should be based around [pkgr](https://github.com/crohr/pkgr), as it is sysadmin-friendly. If this gets merged, then such documentation would block the Adhearsion 3.0 release.

**Comment by bklang** [comment]
:+1:

**Comment by benlangfeld** [comment]
@bklang Do the changes at https://github.com/adhearsion/adhearsion-website/pull/35 fully satisfy your documentation concerns?

**Pull request merged**
