### PR TITLE
Use blocks for all logs

### PR DESCRIPTION
**Pull request by mstate**
Changed the argument passed to all logger.<level> calls from a String to a Block.  Passing a block will avoid evaluation and any String manipulation for log entries that will not be output.  The net effect should be a decrease in the number of objects created and a reduction in CPU overhead for string manipulations and garbage collection of the unused objects.

### CODE REVIEW

**Comment by emcgee** [comment]
Very interesting. Would you have any benchmarks to compare, and are there are cons to switching to blocks from strings?

**Comment by mstate** [comment]
I don't have any formal benchmarks.  I'm currently running 200K calls through it to see how it performs. So, far (anecdotally) it seems to be noticeably faster (about 10%-15%) and the CPU spikes don't rise as high (less to garbage collect I would suspect), so my CPU usage is flatter. From my research, there seems to be only an upside.  I think evaluating the block is a super-fast action without object creation overhead.  So, even if block evaluation added a tiny bit of impact to performance (and I'm not sure it really does), it would only be in trace mode where you would have any deficit. That seems quite reasonable given that, for normal operations, you would be able to avoid all the objects created by the trace logs and possibly the info as well.  I took the idea from the ruby logging page at http://ruby-doc.org/stdlib-1.9.3/libdoc/logger/rdoc/Logger.html#label-How+to+log+a+message (search for evaluated).

**Comment by benlangfeld** [comment]
The majority of these changes are `info` level or higher. It is very rare that someone would run an Adhearsion application without `info` level logging. The majority of logging (at `trace` level) is done in Punchblock, Blather and RubyAMI, which this does not affect. You would probably achieve better performance results modifying those libraries rather than Adhearsion core.

**Comment by bklang** [comment]
@benlangfeld This is a PR against develop, which has Punchblock folded in (Adhearsion 3). Also, if the performance improvement really is 10% (which we should measure to confirm), wouldn't you still think it worthy of inclusion? If it does help, then making similar changes to those other libraries would seem to make sense as well.

**Comment by benlangfeld** [comment]
> This is a PR against develop, which has Punchblock folded in (Adhearsion 3).

Of course, thanks for reminding me.

> Also, if the performance improvement really is 10% (which we should measure to confirm), wouldn't you still think it worthy of inclusion?

Yes. We need to measure this somehow. It doesn't need to be a full formal proof, but something more than anecdote to justify it would be nice.

**Comment by mstate** [comment]
My 200K calls test limits the calls per second, so I can't really measure pure performance.  I can only infer it by average the level of the CPU during the test.  Would we would be able to look at a travis build and see if the test execution time was affected?

The MRI ruby documentation (linked above) seems to clearly say that logging should be done with a block.  Isn't that sufficient?

I will make a similar pull request to the blather and RubyAMI libraries.  Are there any other libraries that you think would be material?

**Comment by benlangfeld** [comment]
>  seems to clearly say that logging should be done with a block

That's not what it says. There is overhead associated with calling a block, which may exceed the overhead of building the string. It has to be handled on a case-by-case basis, not in a blanket fashion like you've done here. Note that you don't automatically win on allocations either, since the block also has to be allocated. https://github.com/adhearsion/adhearsion/pull/588/files#diff-6cf861eba78fb8b65dd928cd9344ce04R354, for example, is almost certainly more expensive now than it was before.

I'm not rejecting this, but it does need to be considered a little more carefully, and I have a very busy week. I'll see what extra feedback I can get you at the weekend.

**Comment by benlangfeld** [comment]
@mstate Might you perhaps split these later commits into separate branches / PRs so that they can be considered independently of this logging change?

As for the cost of this, check this out:

```
>> def foo(&block)
>> block.call
>> end
=> :foo
>> def nofoo(&block)
>> nil
>> end
=> :nofoo
>> def bar(string)
>> string
>> end
=> :bar
>> puts Benchmark.measure { 10000000.times { bar "foo" } }
  1.360000   0.000000   1.360000 (  1.365464)
=> nil
>> puts Benchmark.measure { 10000000.times { foo { "foo" } } }
  7.800000   0.150000   7.950000 (  8.043248)
=> nil
>> puts Benchmark.measure { 10000000.times { nofoo { "foo" } } }
  5.920000   0.140000   6.060000 (  6.096568)
=> nil
```

What this shows is that the block form in itself is very much more expensive than a simple string allocation. It has to be the case that either:

1. the log string is very expensive to create; or
2. the block is highly unlikely to be evaluated.

in order for the block form to work out cheaper. I'd suggest that 2. does not apply to anything INFO or higher, while benchmarks show that it's difficult to build a simple string which is more expensive than even just allocating and passing the block, and that some rendering step (such as an XML node, maybe?) is necessary for this.

I'd be willing to reconsider this change in a more targeted fashion if it can be argued that a particular log string is expensive. A one-shot application of a technique made available by Logger but for which there is no other guidance, however, I can't accept, given the above.

**Pull request closed without merging**
