### PR TITLE
cleanup CI (and some specs)

### PR DESCRIPTION
**Pull request by kares**
as there's likely to come some more changes later, start of with a ~ :green_heart: CI

can split commits into separate PRs if required

previous attempt should be obsolete, closes https://github.com/adhearsion/adhearsion/pull/607

### CODE REVIEW

**Comment by lpradovera** [comment]
Awesome, thank you! Will wait for CI and review.

**Comment by kares** [comment]
great, should have not added that events spec here, its relevant but fixing it is a separate topic.
going to remove that one, for now

**Review by benlangfeld — APPROVED** [review]

**Review by sfgeorge — APPROVED** [review]
This looks great, thank you @kares 👍   Sorry for the delay in reviewing.

During the code review delay a new release of nio4r (2.4.0) has come out, which unfortunately broke the build for all JRuby flavors, because [nio4r-2.4.0 currently lacks a -java package](socketry/nio4r#213).

Let's merge this PR, and deal with the nio4r issue separately in #637

**Comment by sfgeorge** [comment]
New plan - since the build failure blocks this from being merged.  We'll just merge #637 instead and close this PR.

**Comment by kares** [comment]
cool, thanks for handling this ...

**Pull request merged**
